### PR TITLE
Add New admin

### PR DESCRIPTION
**Pull request by fbordeu**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jschueller** [comment]
Could you update to the newest version too ? I want to make sure the transition goes well.

**Comment by jschueller** [comment]
Would you mind updating the version first ? I want to make sure maintainers know what they're doing

**Comment by fbordeu** [comment]
the version of BasicTools? or the version of the feedstock of BasicTools?. 
I'm working with the author  of Eigency to have a conda-forge version also. 
This way the conda-forge package of BasicTools will correctly compiled.

**Comment by jschueller** [comment]
yes, the version of the feedstock

**Comment by fbordeu** [comment]
I can doit but for the moment for the recipe will be broken (for version 1.7.0, build 0) because eigency is not available on conda-forge.

**Comment by fbordeu** [comment]
I just push a branch for v1.8 (https://github.com/fbordeu/basictools-feedstock/tree/V1.8) but is not ready for production. Missing eignecy for the moment.

**Comment by fbordeu** [comment]
any idea when you are going to be able to treat this PR?
Thanks

**Comment by jschueller** [comment]
yes, please first open a new PR with the updated version when its ready to be included

**Comment by fbordeu** [comment]
I dont understand why you refuse to give me admin acces to the feedstock. I am the Main developper of this library!

**Comment by jschueller** [comment]
I'll happily give you access after a successful update, you can update and add yourself in the same PR

**Pull request closed without merging**
