### PR TITLE
MuscatPort

### PR DESCRIPTION
**Pull request by fbordeu**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by fbordeu** [comment]
@conda-forge-admin, please rerend

**Comment by fbordeu** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
This seems like a pretty fundamental change to the recipe - is this still really the same package afterwards? Even if so, note that the feedstock would keep the "basictools" name, so perhaps a new feedstock through staged-recipes is cleaner.

**Comment by fbordeu** [comment]
Hello @h-vetinari, thanks for the interest of my feedstock.

This branch is for the versoin 2.0 of BasicTools (We changed the name of the library). Please read https://conda.discourse.group/t/rename-package-on-conda-forge/352 for more details.

I don't have the intention of merging this PR for the moment. I'm working on the release of BasicTools 2.0 (Muscat 2.0) I use it mainly to test the feedstock infrastructure on Muscat. If I understand well I going to need to create a new feedstock for Muscat and archive the old feedstock. 

I'm thankful of the effort the conda-forge community, and I dont what to abuse in any way the available resources. So all remarks and comments are welcome.

Thanks again,
Felipe

**Comment by h-vetinari** [comment]
> If I understand well I going to need to create a new feedstock for Muscat and archive the old feedstock.

It's not absolutely required, but probably a good idea, because it would be really hard to find `muscat*` packages if the feedstock is still called basictools.

> I'm thankful of the effort the conda-forge community, and I dont what to abuse in any way the available resources.

Thanks for being considerate. No problem to test the integration here while you prepare the release, as long as you're not spamming builds.

**Pull request closed without merging**
