### PR TITLE
1.9.10

### PR DESCRIPTION
**Pull request by fbordeu**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by fbordeu** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
Not sure what went wrong with the rerender here... 🤔 

In general, it's a bit tricky to skip multi-output recipes in a way that actually removes the CI jobs (needs to be skipped on every output). In this case, you might want to add
```
requirements:
  host:
    - python
```
to the global build section (before `outputs:`), to ensure that the `py` has the right value when the skip is calculated. It's a bit arcane, and I don't understand all the details either...

PS. I saw you have
```
        - numpy =1.21  # [py==38]
        - numpy =1.21  # [py==39]
        - numpy =1.21  # [py==310]
        - numpy =1.23.4  # [py==311]
```
You should just leave that as `- numpy` (without selector); our infrastructure takes care of using the oldest available numpy version per python version, modulo NEP 29.

**Comment by h-vetinari** [comment]
Looks like #44 is a bit cleaner. ;-)

**Comment by fbordeu** [comment]
Hi @h-vetinari, thanks for the feed back.

I use " - numpy =1.21  # [py==38]..." because a had some problem building BasicTools. teh build system add the latest numpy version as ta requirement at runtime. If you tell me I dont need to specified a minimal numpy version for the compilation to be pin compatible, then I will remove theses unnecessary lines.

**Pull request closed without merging**
